### ISSUE TITLE
apply mvc principles

### ISSUE THREAD

**Issue by jaenelleisidro** [davehernaez/SevenEleven#2]
you need to create this

com.hernaez.seven_eleven.model.dataaccesslayer
com.hernaez.seven_eleven.model.businesslayer
com.hernaez.seven_eleven.viecontroller.actvitiy
com.hernaez.seven_eleven.other
com.hernaez.seven_eleven.domain

dataaccess layer - contains code related to database and http

business layer - contains the core logic of your project (how login is validated, etc)
*note, youll need to extract this on your activities

viewcontroller.activity - contains activity
*note, add Activity on class name. for example Login should be LoginActivity

domain - contains, classes that are used to hold data. (ex. Person class holds data like name, address,birthday but contains no logic on how to manipulate this data)

other - contains application class and all initialization of models.

**Comment by davehernaez** [comment]
Ok. so meaning lahat ng methods ko na gumagamit ng http and SQLite database access e kailangan ko e separate at ilagay sa bagong java file?

**Comment by jaenelleisidro** [comment]
yup

**Comment by jaenelleisidro** [comment]
yung part na nagloload ng pics using picasso part yun ng view so ilalagay sya viewcontroller
complete variable names, user should be username pass should be password

**Comment by jaenelleisidro** [comment]
yung mga name ng variables camel case dapat. you can easily change this easily via refactoring

**Comment by jaenelleisidro** [comment]
sa mga identifiers like prodid, try to use integers to optimize speed.

**Comment by jaenelleisidro** [comment]
observe proper database field data type. total should be number and so on

**Comment by jaenelleisidro** [comment]
I created a sample for database for data access layer check it out, its called OrderDao. dapat nagcocommunicate lang yung mga layers via domain class. Sa Dao Class, ang pwede lang na methods eh get(id) delete(order) update(order) add(order)... notice yung order na object, Order class yun sa domain folder. apply the same logic kapag bubuuin mo na yung Product Dao. also keep in mind na ang Data access layer or Dal or Dao ay walang business logic, nag-aadd edit delete at select lang sila sa database.

**Comment by jaenelleisidro** [comment]
ViewControler Layer -> Business Layer -> Data access Layer.. ang ibig sabihin nito eh ang pwede lang tawagin ni viewcontroller eh si business layer.. at ang pwede lang tawagin ni business layer eh si dataaccess layer.. hindi pwedeng tumawag si viewcontroller ng function sa data access layer so pakirefactor yung code mo based sa rule na to.

**Comment by jaenelleisidro** [comment]
sa login, pakidsiable yung login button at username at password para di madouble login at mabago yung username password habang naglologin

**Comment by jaenelleisidro** [comment]
pakienable ang line numbers ng android studio para madali mo tong mahanap

AdminPageActivity 

 line 41 and 71 : pakiextract as constant yung user_id, declare ka ng public static final String EXTRA_USERID=“user_id”

line 39 : pakicheck din kung pagkarotate ng screen eh existing pa yung user_id sa extras 

CustomerOrderActivity
line 55,56 : di pwedeng iaccess ni view ang kahit anong Data access layer, dapat ang viewcontroller, business layer lang ang inaccess,tapos si si business layer eh sya lang yung umaaccess sa data access layer.

line 59-62 : gawin mo na lang isang class ito, ProductManager

93-95 : dapat sa dagger mo to ginagawa, gawa ka ng provides dun para iniinject mo na lang lagi for every views na need ito.

line 214 : isang try catch lang ang kailangan mo, pakitanggal yung isa.

line 252 : pakinject ung context at palitan yung getApplicationContext()

line 256 : required ba talaga na dalawang beses mo iexecute to? parang nagsasayang ka ng resources correct me if imwrong.

**Comment by jaenelleisidro** [comment]
after mong magawa yan. learn from those comments and iapply mo sa buong project yung design logic. Saka pakicomment din dito yung username password ng project mo dahil hanggang login pa lang yung narereview ko

**Comment by jaenelleisidro** [comment]
noong nilipat mo sa ibang website yung code mo. pinalitan mo isa isa yung HTTP_DOMAIN.
Ang tawag sa ginawa mo eh shotgun surgery which is a bad effect of a wrong design pattern. sensya di ko sinabi muna para di manosebleed hahaha! Ang gawin mo, gawa ka ng Constant na class, lagay mo yun sa others folder. tapos yun Constant dun mo lagay yung HTTP_DOMAIN para pag lumipat ka ng ibang website, isang palitan lang ang gagawin mo.

**Comment by davehernaez** [comment]
username: user
password: user

username: admin
password: admin

my problema pa rin sa webserver ko, so malamang yun yung reason kaya d ka maka login hehe

**Comment by jaenelleisidro** [comment]
sa userhttpservice.java line 22, pakipalitan mo ng mas maayos na name yung search user, gawin mong login or something similar
