### ISSUE TITLE
java's volatile and synchronized

### ISSUE THREAD

**Issue by jaenelleisidro** [davehernaez/SevenEleven#6]
read regarding this.

explain it's importance.

ill mark this close if correct.

**Comment by davehernaez** [comment]
My basic understanding of Volatile is that it is used to ensure that the thread accesses the latest value updated to a variable every time the variable is updated by another thread and it only accesses a single variable it updates. Volatile allows multiple threads to access and update a variable from the main memory alternatively while Synchronized is used to synchronize a block of codes in the thread memory from the main memory but does not update the variables in the main memory to ensure write safety. Meaning if Volatile is used all threads that access the same variable will have the same value where in Synchronized multiple threads can have different values of the same variables that the threads access.
